---
apiVersion: v1
kind: Namespace
metadata:
  name: aria-k8s

---
apiVersion: v1
kind: Secret
metadata:
  namespace: aria-k8s
  name: collector-client-secret
data:
  COLLECTOR_CLIENT_SECRET: Q01qanppb2R5Wk52ZWQ3Q1VMUmphcDZqcU1hcWdxSFhUSWxNbTdKbDZkVFdrd0F0dm4=

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: aria-k8s
  namespace: aria-k8s
  name: aria-k8s
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
      - networking.k8s.io
      - extensions
      - rbac
      - batch
      - apps
      - ""
    resources:
      - configmaps
      - endpoints
      - events
      - limitranges
      - persistentvolumes
      - persistentvolumeclaims
      - namespaces
      - podtemplates
      - resourcequotas
      - secrets
      - clusterrolebindings
      - services
      - serviceaccounts
      - networkpolicies
      - ingresses
      - ingressclasses
      - rolebindings
      - clusterroles
      - roles
      - cronjobs
      - jobs
      - replicationcontrollers
      - statefulsets
      - daemonsets
      - deployments
      - replicasets
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: aria-k8s
  namespace: aria-k8s
  name: aria-k8s-service-account

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: aria-k8s
  namespace: aria-k8s
  name: aria-k8s
subjects:
  - kind: ServiceAccount
    namespace: aria-k8s
    name: aria-k8s-service-account
roleRef:
  kind: ClusterRole
  name: aria-k8s
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aria-k8s
  name: aria-k8s
  namespace: aria-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aria-k8s
  template:
    metadata:
      labels:
        app: aria-k8s
    spec:
      serviceAccountName: aria-k8s-service-account
      securityContext:
        fsGroup: 9999
        runAsGroup: 9999
        runAsUser: 9999
      volumes:
        - name: collector-client-secret-vol
          secret:
            secretName: collector-client-secret
      containers:
        - name: aria-k8s
          image: "projects.registry.vmware.com/aria/k8s-collector:1.6.3"
          imagePullPolicy: Always
          volumeMounts:
            - name: collector-client-secret-vol
              mountPath: "/etc/aria-k8s-csp-secret"
              readOnly: true
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: 100m
              memory: "64Mi"
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - NET_RAW
          ports:
            - containerPort: 8080
              name: metrics-port
              protocol: TCP
          env:
            - name: CLIENT_ID
              value: "E8mNpJ2WuIPVf1QNeoerSRq1XF0AaWFQ24n"
            - name: CLIENT_SECRET_PATH
              value: "/etc/aria-k8s-csp-secret/COLLECTOR_CLIENT_SECRET"
            - name: CSP_HOST_NAME
              value: "https://console.cloud.vmware.com"
            - name: ORG_ID
              value: "59d6992a-0f38-47e2-b494-bed28736e4b4"
            - name: CLUSTER_NAME
              value: "view-mood"
            - name: CLUSTER_REGION
              value: "westus"
            - name: CLUSTER_CLOUD_PROVIDER
              value: "Azure"
            - name: CLUSTER_CLOUD_ACCOUNT_ID
              value: "1f79e338-9824-4018-9ebd-1711ba044e17"
            - name: COLLECTOR_ID
              value: "2476b3990e21c238e2bc79d7be739449"
            - name: CLUSTER_MANAGED_BY
              value: "true"
            - name: ENVIRONMENT
              value: "prod"