apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mood-painter
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: mood-painter
spec:
 serviceClaims:
  - name: reading
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: rabbitmq-claim