apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mood-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: mood-sensors
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  #source code
  source:
    git:
      url: https://github.com/dektlong/mood-sensors
      ref:
        branch: main
  
  #ServiceClaims are added in runtime

  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/language: java
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location:
          path: /api-docs
        owner: dekt-dev-team2
        system: devx-mood
        description: A set of API endpoints to manage the resources within the my-web-backend app.