apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mood-sensors-apis-dynamic
  description: APIs to interact with the mood-sensors component
spec:
  type: openapi
  lifecycle: development
  owner: dekt-dev-team2
  system: devx-mood
  definition:
   $text: http://mood-sensors.dev.dekt.io/api-docs