#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: carbonblack-config-secret
stringData:
  cbc_api_id: #@ data.values.carbonblack.cbc_api_id
  cbc_api_key: #@ data.values.carbonblack.cbc_api_key
  cbc_org_key: #@ data.values.carbonblack.cbc_org_key
  cbc_saas_url: #@ data.values.carbonblack.cbc_saas_url
