#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: tap-acme-http01-solver
 namespace: tap-gui
imagePullSecrets:
 - name: acme-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: tap-acme-http01-solver
 namespace: metadata-store
imagePullSecrets:
 - name: acme-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: tap-acme-http01-solver
 namespace: app-live-view
imagePullSecrets:
 - name: acme-pull
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: #@ data.values.tap.ingressIssuer
spec:
  acme:
    email: #@ "cert-notification@" + data.values.dns.domain
    privateKeySecretRef:
      name: #@ data.values.tap.ingressIssuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour
          podTemplate:
             spec:
               serviceAccountName: tap-acme-http01-solver

