#@ load("@ytt:data", "data")
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: #@ data.values.tap.prodIngressIssuer
spec:
  acme:
    email: #@ "cert-notification@" + data.values.dns.domain
    privateKeySecretRef:
      name: #@ data.values.tap.ingressIssuer
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: contour
            podTemplate:
              spec:
                serviceAccountName: default