---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dekt-letsencrypt
spec:
  acme:
    email: certificate-notices@dekt.io
    privateKeySecretRef:
      name: dekt-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: contour