#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  annotations:
    tekton.dev/git-0: #@ data.values.deliverable_gitops.server_address
type: kubernetes.io/basic-auth
stringData:
  password: #@ data.values.deliverable_gitops.token
  username: #@ data.values.deliverable_gitops.repository_owner