#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: openai-binding
type: servicebinding.io/openai
stringData:
  type: openai
  provider: sample
  key: #@ data.values.openai.token
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: openai-claim
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: openai-binding
