apiVersion: bindable.database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: inventory-db
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: gcp
  publishConnectionDetailsTo:
    name: inventory-db
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: cloudsql-postgres