#@ load("@ytt:data", "data")
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xWorkloadSpaceBindings.xp.tanzu.vmware.com
  annotations:
          
spec:
  defaultCompositionRef:
    name: xpspace
  group: xp.tanzu.vmware.com
  names:
    kind: XWorkloadSpaceBinding
    plural: xWorkloadSpaceBindings
  claimNames:
    kind: WorkloadSpaceBinding
    plural: WorkloadSpaceBindings
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              id:
                type: string
                description: Space ID that other objects refer to
              clusterNamespace:
                type: object
                properties:
                  id:
                    type: string
                  namespace:
                    type: string

            required:
            - id
            - clusterNamespace
            
           
          status:
            type: object
            properties:
              clusters:
                description: Cluster statuses
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    status:
                      type: string
              
              

