clusters:
  view: # TAP view profile installed
    name: 
    provider: #accepted values: aks,eks,gke 
    nodes: 4
  dev: # TAP interate profile installed
    name: 
    provider: #accepted values: aks,eks,gke  
    nodes: 4 
  stage: #TAP build profile installed
    name: 
    provider: #accepted values: aks,eks,gke 
    nodes: 6 
  prod1: # TAP run profile installed
    name: 
    provider: #accepted values: aks,eks,gke  
    nodes: 3
  prod2: # TAP run profile installed
    name: 
    provider: #accepted values: aks,eks,gke  
    nodes: 3 
  brownfield: #for bronwfield apis demo, SCGW and TSM, no TAP installed
    name: 
    provider: #accepted values: aks,eks,gke 
    nodes: 2 

clouds:
  azure:
    subscriptionID:
    location: # US: westus | UK: ukwest | EU: germanynorth | SIN: eastasia | ANZ: australiasoutheast 
    resourceGroup: 
    nodeType: Standard_DS3_v2 
  aws:
    accountID: 
    IAMuser: 
    region: # US: us-west-1 | UK: eu-west-2 | EU: eu-central-1 | SIN: ap-southeast1 | ANZ: ap-southeast-2
    instanceType: t3.xlarge
  gcp:
    region: # US: us-central1 | UK: europe-west2 | EU: europe-west3 | SIN: asia-southeast1 | ANZ: australia-southeast1
    projectID: 
    machineType: e2-standard-4

private_registry:
  host: 
  username: 
  password: 
  repo: 

tanzu_network:
  username: 
  password: 

tap:
  
  tapVersion: 1.5.0
  carvelBundle: "sha256:79abddbc3b49b44fc368fede0dab93c266ff7c1fe305e2d555ed52d00361b446"
    scanTemplates: #accepted values: carbonblack-private-image-scan-template snyk-private-image-scan-template, private-image-scan-template
    portal: snyk-private-image-scan-template 
    sensors: carbonblack-private-image-scan-template 
    doctor: snyk-private-image-scan-template 
    predictor: private-image-scan-template
    painter: carbonblack-private-image-scan-template 
  appsIngressIssuer:  # used for workloads, accepted values: tap-ingress-selfsigned or your own cert (in which case verify if you need to update .config/secrets/cluster-issue-apps.yaml)
  isvImg: #BYO image name, must be pushed to private_registry/isvs repo

snyk: 
  token: 

openai: 
  token: 

carbonblack:
  cbc_api_id: 
  cbc_api_key: 
  cbc_org_key: 
  cbc_saas_url: 

apps_namespaces:
  dev1:  #for mood-portal single dev workload
  dev2:  #for mood-sensors single dev workload
  team:  #for the DevXmood dev team (mood-portal, mood-sensors, mood-doctor and mood-predictor workloads)
  stageProd:  #for promoting the DevXmood business application to stage and prod

gitops: 
  
  server: #e.g https://github.com
  owner:
  token: #must have read/write permissions for all repos below repo
  resources: # repo must be created prior to installing the demo
    repo:
    # subPath needs to be created and contain at least the following resources: 
    # 1. scan-policy.yaml
    # 2. tekton-pipeline-golang.yaml
    # 3. tekton-pipeline-java.yaml
    # 4. tekton-pipeline-nodejs.yaml
    # 5. snyk-install.yaml !!make sure the snyk_values["metadataStore"] = {"url" value is updated
    # 6. carbonblack-install.yaml !!make sure the snyk_values["metadataStore"] = {"url" value is updated
    #
    # see example at https://github.com/dektlong/gitops-resources/tree/main/resources
    subPath:
  
  deliverables: # repos must be created prior to installing the demo and cloned to the same path as the demo install 
    devRepo:  # dev and team supplychains deliverables will be pushed to /config
    stageRepo: # stage supplychain deliverables will be pushed to /config

  
  

dns:
  domain: 
  sysSubDomain: 
  devSubDomain:
  stageSubDomain: 
  prod1SubDomain: 
  prod2SubDomain: 
  godaddyApiKey: 
  godaddyApiSecret: 

tmc:
  apiToken: 
  clusterGroup: 
