apiVersion: tanzu.vmware.com/v1
kind: SpringCloudGateway
metadata:
  name: mood-brownfield-gateway
spec:
  count: 2
  
  server:
    tls: 
      - hosts:
        - datacheck.gns.dekt.io
        - sentiment.gns.dekt.io
        secretName: mood-tls-cert
  client:
    tls:   
      secretNames: mood-tls-cert
  
  api:
    serverUrl: https://gns.dekt.io
    title: Micro-gateway to contorl 3rd party/legacy API access
    version: 0.1.0
    groupId: brownfield-apis
  
  sso: 
    secret: mood-gw-sso-creds

  cors:
      allowedOrigins:
       - tap-gui.sys.dekt.io
  