apiVersion: bindable.database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: inventory-db
spec:
  parameters:
    #! supported storage sizes: 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768
    storageGB: 32
  compositionSelector:
    matchLabels:
      provider: azure
  publishConnectionDetailsTo:
    name: inventory-db
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: azuresql-postgres