apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test     # (!) required
spec:
  params:
    - name: source-url                       # (!) required
    - name: source-revision                  # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: maven:3-openjdk-11
            script: |-
              cd `mktemp -d`
              wget -qO- $(params.source-url) | tar xvz -m
              mvn test

    # JENKINS INTEGRATION
    #! Required: Include the built-in task that triggers the given job in Jenkins
    #- name: jenkins-task
    #  taskRef:
    #    name: jenkins-task
    #    kind: ClusterTask
    #  params:
    #    - name: source-url
    #      value: $(params.source-url)
    #    - name: source-revision
    #      value: $(params.source-revision)
    #    - name: secret-name
    #      value: $(params.secret-name)
    #    - name: job-name
    #      value: $(params.job-name)
    #    - name: job-params
    #      value: $(params.job-params)